### ISSUE TITLE
Bug:  Missing data service type instance name returns 500 error code.

### ISSUE THREAD

**Issue by tripott** [hyper63/hyper-adapter-couchdb#18]
getting this error when using hyper-connect with a service instance name that does not exist for the data service:

example HTTP call with the bad instance name in the query string

```sh
https://3000-harlequin-mockingbird-r5psl5u7.ws-us21.gitpod.io/api/data?serviceinstancename=default2
```

Example NodeJS/Express route handler:

```js


export default async function (req, res) {
  // connecting to any service type named by the 'serviceinstancename' query string.
  //  Fallback to a service instance name of 'default'
  const serviceinstancename = pathOr(
    'default',
    ['query', 'serviceinstancename'],
    req,
  )
  const hyper = connect(process.env.HYPER, serviceinstancename)

  console.log('data: get: ', req.params.id)
  const result = await hyper.data.get(req.params.id).catch(err => {

	return {ok: false, err}
  })
  console.log('data: get result', result)
  return res.send(result)
}

```

This is what is returned from the example API:  

```js
{
"ok": false,
"err": {
"error": "not_found",
"reason": "Database does not exist.",
"status": 500
}
}
```

- [ ] Change status code to `404`.  
- [ ] Ensure it is not an unhandled exception

**Comment by twilson63** [comment]
@tripott @TillaTheHun0 

What version of this adapter are you currently using in hyper-cloud?

When I curl localhost:6363/data/foo/1 and there is no db, I get `404` Not Found

So the adapter is returning the correct status code.

**Comment by TillaTheHun0** [comment]
@twilson63 currently deployed is `v0.0.18`. Trunk is running `v0.0.23`, as part of El Dorado work, but that hasn't been deployed. We can deploy whenever we'd like.

**Comment by twilson63** [comment]
@TillaTheHun0 

Sounds good, I think this version should correct this issue at least based on running the harness script which runs everything through hyper core and hyper opine

**Comment by twilson63** [comment]
Closing issue for now, we can re-open if the latest version of the couchdb adapter does not resolve this bug.
