### ISSUE TITLE
reduce iterations in `query` and `list` by refactoring to use a `transducer` pattern

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper-adapter-couchdb#36]
We iterate over list of documents in this adapter quite a bit, and we usually do so sequentially -- "filter out these docs", "omit this field on each doc", "add this field". Each of these actions iterates through the array, which is fine for small lists of documents but could potentially have real impacts on performance with large lists of docs.

Instead, we should leverage `transduce` to reduce the number of times we iterate through a list to a single iteration, performing all transformations during that single iteration.

I should be able to refactor the code, and then run the unit tests to ensure nothing is broken

~- [ ] #38~
- [x] queryDocuments
- [x] listDocuments

**Comment by TillaTheHun0** [comment]
I'll also use this opportunity to beef up the test coverage on this adapter. I'm noticing now that it's not where i'd like it to be.

**Comment by twilson63** [comment]
Nice! Great work!

**Comment by TillaTheHun0** [comment]
`bulkDocuments` has a lot of moving parts, so i'd like to do that separately.
