### ISSUE TITLE
bug: regression in 0.0.19 queryDocuments

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper-adapter-couchdb#8]
There seems to be a regression in `queryDocuments` with `0.0.19`. I can make a query with `0.0.18` and get results, but then receive no results with the same query on `0.0.19`. I suspect it has something to do with the `deepSwap` utility.

Haven't had time to investigate, but for now, dropping back down to the `0.0.18` version works. Will need to look into this.

**Comment by twilson63** [comment]
That is weird, it works for me using hyper-test, can you provide an example of your query?

**Comment by twilson63** [comment]
This query is not returning results in hyper-cloud

```
{
  slug: {
    $in: ['acnt-****']
  }
}
```

Need to simulate in hyper-test to confirm issue is with couchdb adapter

**Comment by TillaTheHun0** [comment]
#15 seemed to fix some of the queries, but not all. Here is a query that doesn't seem to be working. I get results with v0.0.18, but no results on v0.0.22

```
{
  "members": {
    "$elemMatch": {
      "id": {
        "$in": [ "user-****" ]
      }
    }
  },
  "docType": "account"
}
```

**Comment by twilson63** [comment]
So you have an array of members that have `{ "id": ...}` 

So I don't know how to determine when a doc is using a `id` versus the `_id` - should we consider just using `_id` because it is private and we will not have to deal with these issues.
